Create and manipulate 1D, 2D and 3D arrays

In [1]:
import numpy as np

# 1D array
a = np.array([10, 20, 30, 40, 50])
print(a)

# 2D array
b = np.array([[1, 2, 3], [4, 5, 6]])
print(b)

# 3D array
c = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
print(c)

[10 20 30 40 50]
[[1 2 3]
 [4 5 6]]
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


Vectorised operations

In [2]:
a = np.array([1, 2, 3, 4, 5])

print(a + 10)
print(a * 2)

print("Sum:", np.sum(a))
print("Mean:", np.mean(a))

[11 12 13 14 15]
[ 2  4  6  8 10]
Sum: 15
Mean: 3.0


Boolean masking and fancy indexing

In [4]:
# boolean masking
a = np.array([10, 20, 30, 40, 50])
print(a[a > 25])

# fancy indexing
print(a[[0, 2, 4]])

[30 40 50]
[10 30 50]


Statistical measures

In [5]:
a = np.array([10, 20, 30, 40, 50])

print("Mean:", np.mean(a))
print("Standard Deviation:", np.std(a))
print("75th Percentile:", np.percentile(a, 75))

# Correlation:
x = np.array([10, 20, 30, 40, 50])
y = np.array([12, 18, 35, 38, 55])

print("Correlation:", np.corrcoef(x, y)[0, 1])

Mean: 30.0
Standard Deviation: 14.142135623730951
75th Percentile: 40.0
Correlation: 0.9803055511712668


# NumPy vs Python loop performance

## Use 1 million values:

In [6]:
import numpy as np
import time

data = np.arange(1000000)

# Python loop
start = time.time()

result = []
for x in data:
    result.append(x * 2)

loop_time = time.time() - start

# NumPy
start = time.time()

result = data * 2

numpy_time = time.time() - start

print("Python Loop:", loop_time)
print("NumPy:", numpy_time)

Python Loop: 0.196244478225708
NumPy: 0.007541179656982422
